### ISSUE TITLE
Add support for SVG imports?

### ISSUE THREAD

**Issue by Coolicc** [fayez-nazzal/react-rollup-component-library#1]
Thanks for sharing this boilerplate, I've spent a while trying to find a modern, working and minimal boilerplate for this, and yours is absolutely perfect! 😊

However, if there's one thing that'd be great to add - it is support for SVG imports as React Components for easy use of icons, as one would in react apps. Would ideally work with TypeScript, in  components, stories and testing files ofc. 

*An example of what I mean*
```tsx
import { ReactComponent as Logo } from "../assets/Logo.svg";

// this too would be fine:
// import Logo from "../assets/Logo.svg";

const Example: React.FC<Example> = () => (
  <div>
    <Logo /> Company
  </div>
);
```

**Comment by fayez-nazzal** [comment]
I added SVG support inside the boilerplate, configured for both rollup and webpack ( for storybook support ).

Feel free to reopen if necessary.

Thank you :)

**Comment by Coolicc** [comment]
Hi, thank you, that's great! 😊 However, SVGs does not seem to work with stories or test files. 

I added an extra prop to the Example for passing a Logo (with type any as well, purely for demonstration). And then imported the SVG in the story and test files:
```tsx
import { ReactComponent as Logo } from "./rollup.svg";

// alternatively, I get the same error when importing it this way:
import Logo from "./rollup.svg";
```

In **both** files, there is a TypeScript error when trying to import SVGs:
```tsx
Cannot find module './rollup.svg' or its corresponding type declarations.ts(2307)
```

This is then accompanied by separate error messages for the different files.

## Test
**Without** importing any SVGs in the test file, I do get two errors just from having the Rollup SVG in the Example component it is trying to render:
```tsx
Warning: <ReactComponent /> is using incorrect casing. 
Use PascalCase for React components, or lowercase for HTML elements.
 
Warning: The tag <ReactComponent> is unrecognised in this browser. 
If you meant to render a React component, start its name with an uppercase letter.
```
I get the same errors when I import an SVG in the actual test file, and pass it to the Example component to have a custom logo rendered.

## Stories
When trying to again import an SVG and pass it as a prop to the component, in stories, it sees it as undefined.
```tsx
Element type is invalid: expected a string (for built-in components) or 
a class/function (for composite components) but got: undefined. 
You likely forgot to export your component from the file it's defined in, 
or you might have mixed up default and named imports.
```

Just wanted to make you aware 😊

**Comment by fayez-nazzal** [comment]
> Hi, thank you, that's great! 😊 However, SVGs does not seem to work with stories or test files.
> 
> I added an extra prop to the Example for passing a Logo (with type any as well, purely for demonstration). And then imported the SVG in the story and test files:
> 
> ```tsx
> import { ReactComponent as Logo } from "./rollup.svg";
> 
> // alternatively, I get the same error when importing it this way:
> import Logo from "./rollup.svg";
> ```
> 
> In **both** files, there is a TypeScript error when trying to import SVGs:
> 
> ```tsx
> Cannot find module './rollup.svg' or its corresponding type declarations.ts(2307)
> ```
> 
> This is then accompanied by separate error messages for the different files.
> 
> ## Test
> **Without** importing any SVGs in the test file, I do get two errors just from having the Rollup SVG in the Example component it is trying to render:
> 
> ```tsx
> Warning: <ReactComponent /> is using incorrect casing. 
> Use PascalCase for React components, or lowercase for HTML elements.
>  
> Warning: The tag <ReactComponent> is unrecognised in this browser. 
> If you meant to render a React component, start its name with an uppercase letter.
> ```
> 
> I get the same errors when I import an SVG in the actual test file, and pass it to the Example component to have a custom logo rendered.
> 
> ## Stories
> When trying to again import an SVG and pass it as a prop to the component, in stories, it sees it as undefined.
> 
> ```tsx
> Element type is invalid: expected a string (for built-in components) or 
> a class/function (for composite components) but got: undefined. 
> You likely forgot to export your component from the file it's defined in, 
> or you might have mixed up default and named imports.
> ```
> 
> Just wanted to make you aware 😊

Thank you for reporting back, I fixed the issues you mentioned, you can see the new example code in the last two commits.

![image](https://user-images.githubusercontent.com/49946791/158988198-871ba4b1-d9db-4851-bfea-2270cbbcdcf6.png)

**Comment by Coolicc** [comment]
It works great, thank you very much! It's honestly an awesome boilerplate, really helped me a lot 🙂
